---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  remote_user: '{{ primary_user }}'
  become: true
  become_method: su
  become_user: root
  roles:
    - common

- name: apply dashboard configs
  hosts: dashboard
  remote_user: '{{ primary_user }}'
  become: true
  become_method: su
  become_user: root
  roles:
    - dashboard
    - role: ansible_role_autologin
      autologin_user:
          name:  dash
          group: users
      autologin_startup: /home/dash/scripts/attachtmux.sh
      # https://github.com/ntd/ansible-role-autologin
    - reboot